version: 0.2

env:
  variables:
    IMAGE_DB: "middleware/db"
    IMAGE_QUEUE: "middleware/queue"
  parameter-store:
    GITHUB_USER: "/build/GITHUB_USER"
    GITHUB_TOKEN: "/build/GITHUB_TOKEN"

phases:
  install:
    runtime-versions:
      golang: 1.14
    commands:
      - echo "machine github.com" > ~/.netrc
      - echo "login ${GITHUB_USER}" >> ~/.netrc
      - echo "password ${GITHUB_TOKEN}" >> ~/.netrc
  pre_build:
    commands:
      - echo Setting environment variables
      - PKG=${CODEBUILD_SRC_DIR}/pkg
      - MIDDLEWARE=${CODEBUILD_SRC_DIR}/local
      - BUILD_OPT="--no-cache --pull"
      - TAG=v0.0.${CODEBUILD_BUILD_NUMBER}
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
      - REGISTORY=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

      - echo Testing the sources...
      - cd ${PKG}/portscan   && go test ./...

      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})
  build:
    commands:
      - echo Build gateway started on `date`
      - echo Pushing the Docker images...
      - cd ${MIDDLEWARE}/db   && docker build ${BUILD_OPT} -t ${IMAGE_DB}:${TAG} .
      - cd ${MIDDLEWARE}/sqs  && docker build ${BUILD_OPT} -t ${IMAGE_QUEUE}:${TAG} .

