version: 0.2

env:
  variables:
    REGISTRY: "public.ecr.aws/risken"
    IMAGE_PREFIX: "middleware"
  parameter-store:
    GITHUB_USER: "/build/GITHUB_USER"
    GITHUB_TOKEN: "/build/GITHUB_TOKEN"
    DOCKER_USER: "/build/DOCKER_USER"
    DOCKER_TOKEN: "/build/DOCKER_TOKEN"

phases:
  install:
    runtime-versions:
      golang: 1.14
    commands:
      - echo "machine github.com" > ~/.netrc
      - echo "login ${GITHUB_USER}" >> ~/.netrc
      - echo "password ${GITHUB_TOKEN}" >> ~/.netrc
  pre_build:
    commands:
      - echo Setting environment variables
      - PKG=${CODEBUILD_SRC_DIR}/pkg
      - MIDDLEWARE=${CODEBUILD_SRC_DIR}/middleware
      - BUILD_OPT="--no-cache --pull"
      - TAG=${CODEBUILD_WEBHOOK_TRIGGER#tag/}
      - AWS_XRAY_SDK_DISABLED=TRUE

      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin  ${REGISTRY}

      - |
        #!/bin/bash
        if [[ -n "${DOCKER_USER}" ]] && [[ -n "${DOCKER_TOKEN}" ]]; then
          echo 'Logging in to Docker Hub...'
          echo "$DOCKER_TOKEN" | docker login -u $DOCKER_USER --password-stdin
        fi

      - echo Testing go package
      - cd ${PKG}/database/sql && go test ./...
      - cd ${PKG}/logging      && go test ./...
      - cd ${PKG}/portscan     && go test ./...
      - cd ${PKG}/sqs          && go test ./...
      - cd ${PKG}/xray         && go test ./...
  build:
    commands:
      - echo Build gateway started on `date`
      - echo Pushing the Docker images...
      - cd ${MIDDLEWARE} && make build-ci -j BUILD_OPT="${BUILD_OPT}" IMAGE_PREFIX=${IMAGE_PREFIX} IMAGE_TAG=${TAG} IMAGE_REGISTRY=${REGISTRY}

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - cd ${MIDDLEWARE} && make push-image -j IMAGE_PREFIX=${IMAGE_PREFIX} IMAGE_TAG=${TAG} IMAGE_REGISTRY=${REGISTRY}
      - cd ${MIDDLEWARE} && make push-image -j IMAGE_PREFIX=${IMAGE_PREFIX} IMAGE_TAG=latest IMAGE_REGISTRY=${REGISTRY}
