version: 0.2

env:
  variables:
    REGISTRY: "public.ecr.aws/risken"
    REPOSITORY: "middleware/db-base"
  parameter-store:
    GITHUB_USER: "/build/GITHUB_USER"
    GITHUB_TOKEN: "/build/GITHUB_TOKEN"

phases:
  install:
    commands:
      - echo "machine github.com" > ~/.netrc
      - echo "login ${GITHUB_USER}" >> ~/.netrc
      - echo "password ${GITHUB_TOKEN}" >> ~/.netrc
      - export DOCKER_CLI_EXPERIMENTAL=enabled
  pre_build:
    commands:
      - echo Setting environment variables
      - BUILD_OPT="--no-cache --pull"

      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${REGISTRY}
  build:
    commands:
      - echo Build applicationscan base image manifest started on `date`
      - TAG=${MYSQL_VERSION}
      # version tag
      - docker manifest create ${REGISTRY}/${REPOSITORY}:${TAG} ${REGISTRY}/${REPOSITORY}:${TAG}_linux_amd64 ${REGISTRY}/${REPOSITORY}:${TAG}_linux_arm64
      - docker manifest annotate --arch amd64 ${REGISTRY}/${REPOSITORY}:${TAG} ${REGISTRY}/${REPOSITORY}:${TAG}_linux_amd64
      - docker manifest annotate --arch arm64 ${REGISTRY}/${REPOSITORY}:${TAG} ${REGISTRY}/${REPOSITORY}:${TAG}_linux_arm64
      # latest
      - docker manifest create ${REGISTRY}/${REPOSITORY}:latest ${REGISTRY}/${REPOSITORY}:${TAG}_linux_amd64 ${REGISTRY}/${REPOSITORY}:${TAG}_linux_arm64
      - docker manifest annotate --arch amd64 ${REGISTRY}/${REPOSITORY}:latest ${REGISTRY}/${REPOSITORY}:${TAG}_linux_amd64
      - docker manifest annotate --arch arm64 ${REGISTRY}/${REPOSITORY}:latest ${REGISTRY}/${REPOSITORY}:${TAG}_linux_arm64

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker manifest...
      # push manifests
      - docker manifest push ${REGISTRY}/${REPOSITORY}:${TAG}
      - docker manifest push ${REGISTRY}/${REPOSITORY}:latest
      # inspect
      - docker manifest inspect ${REGISTRY}/${REPOSITORY}:${TAG}
      - docker manifest inspect ${REGISTRY}/${REPOSITORY}:latest
