use mimosa;

CREATE TABLE diagnosis (
  diagnosis_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  project_id INT UNSIGNED NOT NULL,
  name VARCHAR(50) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(diagnosis_id)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin AUTO_INCREMENT = 1001;

CREATE TABLE diagnosis_data_source (
  diagnosis_data_source_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  description VARCHAR(200) NOT NULL,
  max_score FLOAT(5,2) UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(diagnosis_data_source_id)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin AUTO_INCREMENT = 1001;

CREATE TABLE rel_diagnosis_data_source (
  rel_diagnosis_data_source_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  diagnosis_data_source_id INT UNSIGNED NOT NULL,
  diagnosis_id INT UNSIGNED NOT NULL,
  project_id INT UNSIGNED NOT NULL,
  record_id VARCHAR(50),
  jira_id VARCHAR(50),
  jira_key VARCHAR(50),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(rel_diagnosis_data_source_id),
  UNIQUE KEY project_by_resource (diagnosis_id,diagnosis_data_source_id,jira_id,jira_key,record_id)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin AUTO_INCREMENT = 1001;