version: 0.2

env:
  variables:
    IMAGE_APPLICATIONSCAN_BASE: "diagnosis/applicationscan-base"

phases:
  install:
    commands:
      - export DOCKER_CLI_EXPERIMENTAL=enabled
  pre_build:
    commands:
      - echo Setting environment variables
      - BUILD_OPT="--no-cache --pull"
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
      - REGISTORY="public.ecr.aws/risken"
      - REPO_REGION="us-east-1"

      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region ${REPO_REGION} | docker login --username AWS --password-stdin ${REGISTORY}
  build:
    commands:
      - echo Build applicationscan base image manifest started on `date`
      - TAG=${APPLICATIONSCAN_VERSION}
      # version tag
      - docker manifest create ${REGISTORY}/${IMAGE_APPLICATIONSCAN_BASE}:${TAG} ${REGISTORY}/${IMAGE_APPLICATIONSCAN_BASE}:${TAG}_linux_amd64 ${REGISTORY}/${IMAGE_APPLICATIONSCAN_BASE}:${TAG}_linux_arm64
      - docker manifest annotate --arch amd64 ${REGISTORY}/${IMAGE_APPLICATIONSCAN_BASE}:${TAG} ${REGISTORY}/${IMAGE_APPLICATIONSCAN_BASE}:${TAG}_linux_amd64
      - docker manifest annotate --arch arm64 ${REGISTORY}/${IMAGE_APPLICATIONSCAN_BASE}:${TAG} ${REGISTORY}/${IMAGE_APPLICATIONSCAN_BASE}:${TAG}_linux_arm64
      # latest
      - docker manifest create ${REGISTORY}/${IMAGE_APPLICATIONSCAN_BASE}:latest ${REGISTORY}/${IMAGE_APPLICATIONSCAN_BASE}:${TAG}_linux_amd64 ${REGISTORY}/${IMAGE_APPLICATIONSCAN_BASE}:${TAG}_linux_arm64
      - docker manifest annotate --arch amd64 ${REGISTORY}/${IMAGE_APPLICATIONSCAN_BASE}:latest ${REGISTORY}/${IMAGE_APPLICATIONSCAN_BASE}:${TAG}_linux_amd64
      - docker manifest annotate --arch arm64 ${REGISTORY}/${IMAGE_APPLICATIONSCAN_BASE}:latest ${REGISTORY}/${IMAGE_APPLICATIONSCAN_BASE}:${TAG}_linux_arm64

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker manifest...
      # push manifests
      - docker manifest push ${REGISTORY}/${IMAGE_APPLICATIONSCAN_BASE}:${TAG}
      - docker manifest push ${REGISTORY}/${IMAGE_APPLICATIONSCAN_BASE}:latest
      # inspect
      - docker manifest inspect ${REGISTORY}/${IMAGE_APPLICATIONSCAN_BASE}:${TAG}
      - docker manifest inspect ${REGISTORY}/${IMAGE_APPLICATIONSCAN_BASE}:latest
