version: 0.2

env:
  variables:
    REGISTRY: "public.ecr.aws/risken"
    IMAGE_SUBDOMAIN_BASE: "osint/subdomain-base"
  parameter-store:
    GITHUB_USER: "/build/GITHUB_USER"
    GITHUB_TOKEN: "/build/GITHUB_TOKEN"

phases:
  install:
    commands:
      - echo "machine github.com" > ~/.netrc
      - echo "login ${GITHUB_USER}" >> ~/.netrc
      - echo "password ${GITHUB_TOKEN}" >> ~/.netrc
  pre_build:
    commands:
      - echo Setting environment variables
      - BUILD_OPT="--no-cache --pull"

      - echo Logging in to Amazon ECR...
      - codebuild-breakpoint
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin  ${REGISTRY}
  build:
    commands:
      - echo Build subdomain base image started on `date`
      - TAG=${SUBDOMAIN_BASE_VERSION}_${OS}_${ARCH}
      - cd dockers/subdomain-base
      - docker build ${BUILD_OPT} -t ${IMAGE_SUBDOMAIN_BASE}:${TAG} .

      - echo Tagging the images...
      # tag the specific version
      - docker tag ${IMAGE_SUBDOMAIN_BASE}:${TAG} ${REGISTRY}/${IMAGE_SUBDOMAIN_BASE}:${TAG}

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...

      # specific version
      - docker push ${REGISTRY}/${IMAGE_SUBDOMAIN_BASE}:${TAG}
