batch:
  build-graph:
    - identifier: build_amd64
      buildspec: codebuild/dependency-base/buildspec-image.yml
      env:
        compute-type: BUILD_GENERAL1_SMALL
        image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        privileged-mode: true
        type: LINUX_CONTAINER
        variables:
          OS: linux
          ARCH: amd64
          DEPENDENCY_BASE_VERSION: v0.0.2
    - identifier: build_arm64
      buildspec: codebuild/dependency-base/buildspec-image.yml
      env:
        compute-type: BUILD_GENERAL1_SMALL
        image: aws/codebuild/amazonlinux2-aarch64-standard:2.0
        privileged-mode: true
        type: ARM_CONTAINER
        variables:
          OS: linux
          ARCH: arm64
          DEPENDENCY_BASE_VERSION: v0.0.2
    - identifier: build_manifest
      buildspec: codebuild/dependency-base/buildspec-manifest.yml
      env:
        compute-type: BUILD_GENERAL1_SMALL
        image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        privileged-mode: true
        type: LINUX_CONTAINER
        variables:
          DEPENDENCY_BASE_VERSION: v0.0.2
      depend-on:
        - build_amd64
        - build_arm64


